version: '3'

services:
  kafka-broker:
    image: bitnami/kafka
    container_name: cloud-stream-kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper
    container_name: cloud-stream-kafka-zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
